[project]
name = "jaxmat"
version = "0.0.1"
description = "Automated material constitutive modeling in JAX"
readme = "README.md"
authors = [
    { name = "Jeremy Bleyer", email = "jeremy.bleyer@enpc.fr" }
]
license = { text = "GNU GPLv3" }  # Replace or remove if not using MIT
keywords = ["material science", "machine learning", "material modeling", "solid mechanics", "automatic differentiation"]
requires-python = ">=3.10"
dependencies = [
    "jax[cuda12]==0.6.1",
    "jaxlib==0.6.1",
    "nvidia-cublas-cu12",
    "optax",
    "equinox",
    "diffrax",
    "optimistix"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
